Algoritmo "PAR OU IMPAR"

Var
   N : Inteiro
Inicio

      EscrevaL("_________________")
      EscrevaL("                ")
      EscrevaL(" PAR OU IMPAR ")
      Escreval("_________________")
      EscrevaL("                ")
      
      Escreval("Digite um número qualquer")
      Leia (N)

      Se ( N % 2 = 0 ) entao
           Escreval ("O número", N, " é PAR")
      
      Senao
           Escreval ("Este numero",N , " é IMPAR")
      
      FimSe

Fimalgoritmo